GET https://acessoaccount.herokuapp.com/api/Account

###
GET https://acessoaccount.herokuapp.com/api/Account/95293974

###
POST https://acessoaccount.herokuapp.com/api/Account
Content-Type: application/json

{
  "accountNumber": "07153783",
  "value": 10,
  "type": "Credit"
}

###
GET http://localhost:3000

###
POST http://localhost:3000/api/fund-transfer
Content-Type: application/json

{
  "accountOrigin": "22925432",
  "accountDestination": "01920461",
  "value": "5.000009"
}

###
GET http://localhost:3000/api/fund-transfer/180802c1-5ca8-4630-b8f5-7456f061f164

###

POST https://hidden-fortress-80978.herokuapp.com/api/fund-transfer
Content-Type: application/json

{
  "accountOrigin": "22925432",
  "accountDestination": "01920461",
  "value": "5.000009"
}

###

GET https://hidden-fortress-80978.herokuapp.com/api/fund-transfer/921c889a-065b-4f46-8859-4dbb244862ef

###