GET https://acessoaccount.herokuapp.com/api/Account

###
GET https://acessoaccount.herokuapp.com/api/Account/95293974

###
POST https://acessoaccount.herokuapp.com/api/Account
Content-Type: application/json

{
  "accountNumber": "07153783",
  "value": 10,
  "type": "Credit"
}

###
GET http://localhost:3000

###
POST http://localhost:3000/api/fund-transfer
Content-Type: application/json

{
  "accountOrigin": "22925432",
  "accountDestination": "01920461",
  "value": "5.000009"
}

###
GET http://localhost:3000/api/fund-transfer/fed235aa-87f1-44d7-85fc-bb7b1ab03d9e

###

POST https://teste-acesso.herokuapp.com/api/fund-transfer
Content-Type: application/json

{
  "accountOrigin": "11890010",
  "accountDestination": "82771260",
  "value": 90,
  "email": "jeser73705@sicmag.com"
}

###

GET https://teste-acesso.herokuapp.com/api/fund-transfer/31a86270-fcd8-4ec5-867f-1dc01cc5d757

###
